ROLLBACK;

DROP SEQUENCE EATME_SEQ;
DROP TABLE EATME_BOARD;
DROP SEQUENCE COOKME_SEQ;
DROP TABLE COOKME_BOARD;
DROP SEQUENCE TALKME_SEQ;
DROP TABLE TALKME_BOARD;
DROP SEQUENCE REPLY_SEQ;
DROP TABLE REPLY;
DROP SEQUENCE LEARNME_SEQ;
DROP TABLE LEARNME_BOARD;
DROP SEQUENCE DESSERT_SEQ;
DROP TABLE DESSERT_INFORM;
DROP TABLE ADMIN_DESSERT;
DROP TABLE CUSTOMER;
DROP SEQUENCE LEVEL_SEQ;
DROP TABLE CUSTOMER_LEVEL;


-- 레벨 테이블
DROP SEQUENCE LEVEL_SEQ;
DROP TABLE CUSTOMER_LEVEL;

CREATE SEQUENCE LEVEL_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE CUSTOMER_LEVEL(
    LNUM NUMBER(2) PRIMARY KEY,
    LNAME VARCHAR2(100) NOT NULL UNIQUE);

SELECT * FROM CUSTOMER_LEVEL;

-- 레벨 등록
INSERT INTO CUSTOMER_LEVEL(LNUM, LNAME) VALUES (LEVEL_SEQ.NEXTVAL, '양아치 앨리스');
INSERT INTO CUSTOMER_LEVEL(LNUM, LNAME) VALUES (LEVEL_SEQ.NEXTVAL, '배고픈 앨리스');
INSERT INTO CUSTOMER_LEVEL(LNUM, LNAME) VALUES (LEVEL_SEQ.NEXTVAL, '만찬중 앨리스');
INSERT INTO CUSTOMER_LEVEL(LNUM, LNAME) VALUES (LEVEL_SEQ.NEXTVAL, '배부른 앨리스');
INSERT INTO CUSTOMER_LEVEL(LNUM, LNAME) VALUES (LEVEL_SEQ.NEXTVAL, '돌아간 앨리스');

-----------------------------------------------------------------------------------
-- CUSTOMER 테이블

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    CID VARCHAR2(30) PRIMARY KEY,
    CPW VARCHAR2(30) NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    CNICK VARCHAR2(100) NOT NULL UNIQUE,
    LNUM NUMBER(2) REFERENCES CUSTOMER_LEVEL,
    CBIRTH DATE NOT NULL,
    CGENDER VARCHAR2(10),
    CPHONE1 VARCHAR2(5),
    CPHONE2 VARCHAR2(5),
    CPHONE3 VARCHAR2(5));

SELECT * FROM CUSTOMER;

--중복아이디 확인
SELECT * FROM CUSTOMER WHERE CID='aaa';

--회원가입    
INSERT INTO CUSTOMER(CID, CPW, CNAME, CNICK, LNUM, CBIRTH, CGENDER, CPHONE1, CPHONE2, CPHONE3) VALUES ('aaa', '111', '라이언', '디저트나라의 라이언', 2, '1994-11-08', 'MALE', 010,111,1111);

INSERT INTO CUSTOMER(CID, CPW, CNAME, CNICK, LNUM, CBIRTH, CGENDER, CPHONE1, CPHONE2, CPHONE3) VALUES ('abb', '222', '라이언', '아이스 라이언', 2, '1994-11-08', 'MALE', 010,111,1111);

--로그인
SELECT * FROM CUSTOMER WHERE CID='aaa';

--회원정보 수정
UPDATE CUSTOMER SET CPW='123', CNAME='라이언', CNICK='마카롱라이언', LNUM=3, CBIRTH='1994-10-08', CGENDER='M', CPHONE1=NULL, CPHONE2=NULL, CPHONE3=NULL WHERE CID='aaa';

--아이디로 회원정보 가져오기
SELECT * FROM CUSTOMER WHERE CID='aaa';
SELECT C.*, LNAME FROM CUSTOMER C, CUSTOMER_LEVEL L WHERE C.LNUM=L.LNUM AND CID='aaa';

--전체회원수 출력하기
SELECT COUNT(*) FROM CUSTOMER;

--레벨순으로 START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, C.* FROM (SELECT C.*, LNAME FROM CUSTOMER C, CUSTOMER_LEVEL L WHERE C.LNUM=L.LNUM ORDER BY CID DESC, CID) C) WHERE RN BETWEEN 1 AND 5;

--닉네임으로 검색하기 (목록)
SELECT * FROM CUSTOMER WHERE CNICK='마카롱라이언';

--회원 레벨별 검색하기 (목록)
SELECT * FROM CUSTOMER C, CUSTOMER_LEVEL L WHERE C.LNUM = L.LNUM AND LNAME = 'BRONZE';

--특정회원 레벨 변경하기
UPDATE CUSTOMER SET LNUM = 2 WHERE CID='aaa';

SELECT * FROM CUSTOMER C, CUSTOMER_LEVEL L WHERE C.LNUM=L.LNUM;

--회원탈퇴
UPDATE CUSTOMER SET LNUM = 5 WHERE CID='aaa';

COMMIT;
------------------------------------------------------------------------------------------------------------
--관리자
DROP TABLE ADMIN_DESSERT;

CREATE TABLE ADMIN_DESSERT(
    AID VARCHAR(50) PRIMARY KEY,
    APW VARCHAR(50) NOT NULL,
    ANAME VARCHAR(100) NOT NULL);
    
INSERT INTO ADMIN_DESSERT(AID, APW, ANAME) VALUES ('dessertking','wonder59','이상한 디저트 관리자');

--관리자 로그인
SELECT * FROM ADMIN_DESSERT WHERE AID='dessertking';

------------------------------------------------------------------------------------------------------------------------
-- DESSERT INFORM 테이블
DROP SEQUENCE DESSERT_SEQ;
DROP TABLE DESSERT_INFORM;

CREATE SEQUENCE DESSERT_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE DESSERT_INFORM(
    DINUM NUMBER(6) PRIMARY KEY,
    AID VARCHAR2(50) REFERENCES ADMIN_DESSERT,
    DISUBJECT VARCHAR2(500) NOT NULL,
    DICONTENT CLOB NOT NULL,
    DIFILENAME01 VARCHAR2(100) NOT NULL,
    DIFILENAME02 VARCHAR2(100),
    DIFILENAME03 VARCHAR2(100),
    DIFILENAME04 VARCHAR2(100),
    DIFILENAME05 VARCHAR2(100),
    DIDATE DATE DEFAULT SYSDATE,
    DIHIT NUMBER(6) DEFAULT 0,
    DIIP VARCHAR(20) NOT NULL);


--디저트 종류와 정보 소개글 입력---------------------------
-- 총 글 갯수
SELECT COUNT(*) FROM DESSERT_INFORM;

--조회수 올리기
UPDATE DESSERT_INFORM SET DIHIT = DIHIT + 1 WHERE DINUM=1;

--상세글 보기
SELECT * FROM DESSERT_INFORM WHERE DINUM=1;
                
--글 작성
INSERT INTO DESSERT_INFORM(DINUM, AID, DISUBJECT, DICONTENT, DIFILENAME01, DIFILENAME02, DIFILENAME03, DIFILENAME04, DIFILENAME05, DIIP) 
    VALUES (DESSERT_SEQ.NEXTVAL, 'dessertking', 'SUBJECT', 'CONTENT', 'TESTIMG.JPG', NULL, NULL, NULL, NULL, '192.168.10.151');
  
--수정글 보기
SELECT * FROM DESSERT_INFORM WHERE DINUM=1;  

--글 수정
UPDATE DESSERT_INFORM SET DISUBJECT='TEST SUBJECT', DICONTENT='TEST CONTENT', DIFILENAME01='TESTIMG.JPG', DIFILENAME02=NULL, DIFILENAME03=NULL, DIFILENAME04=NULL, DIFILENAME05=NULL, DIIP='192.168.10.151' WHERE DINUM=1;

--글 삭제
DELETE DESSERT_INFORM WHERE DINUM=1;

--START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM DESSERT_INFORM ORDER BY DINUM DESC) A) WHERE RN BETWEEN 1 AND 2; 

COMMIT;
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- LEARNME TABLE
DROP SEQUENCE LEARNME_SEQ;
DROP TABLE LEARNME_BOARD;

CREATE SEQUENCE LEARNME_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE LEARNME_BOARD(
    LBNUM NUMBER(6) PRIMARY KEY,
    CID VARCHAR2(30) REFERENCES CUSTOMER,
    AID VARCHAR2(30) REFERENCES ADMIN_DESSERT,
    LBSUBJECT VARCHAR2(500) NOT NULL,
    LBCONTENT CLOB NOT NULL,
    LBFILENAME01 VARCHAR2(100) DEFAULT 'NOIMG.jpg',
    LBFILENAME02 VARCHAR2(100),
    LBFILENAME03 VARCHAR2(100),
    LBDATE DATE DEFAULT SYSDATE,
    LBHIT NUMBER(6) DEFAULT 0,
    LBIP VARCHAR2(20) NOT NULL);

-- 총 글 갯수
SELECT COUNT(*) FROM LEARNME_BOARD;

--조회수 올리기
UPDATE LEARNME_BOARD SET LBHIT = LBHIT + 1 WHERE LBNUM=1;

--상세글 보기
SELECT LB.*, (SELECT CNICK FROM CUSTOMER C WHERE C.CID=LB.CID) CNICK,
    (SELECT ANAME FROM ADMIN_DESSERT A WHERE A.AID=LB.AID) ANAME FROM LEARNME_BOARD LB WHERE LBNUM = 1;

--글 등록(회원)
INSERT INTO LEARNME_BOARD(LBNUM, CID, LBSUBJECT, LBCONTENT, LBFILENAME01, LBFILENAME02, LBFILENAME03, LBIP)
    VALUES (LEARNME_SEQ.NEXTVAL,'aaa','회원','나는 회원이다', NULL, NULL, NULL, '192.168.10.151');
--글 등록(관리자)
INSERT INTO LEARNME_BOARD(LBNUM, AID, LBSUBJECT, LBCONTENT, LBFILENAME01, LBFILENAME02, LBFILENAME03, LBIP)
    VALUES (LEARNME_SEQ.NEXTVAL,'dessertking','관리자','나는 이상한 디저트관리자일까? 이상한디저트 관리자일까?', NULL, NULL, NULL, '192.168.10.151');

--수정글 보기
SELECT LB.*, (SELECT CNICK FROM CUSTOMER C WHERE C.CID=LB.CID) CNICK,
    (SELECT ANAME FROM ADMIN_DESSERT A WHERE A.AID=LB.AID) ANAME FROM LEARNME_BOARD LB WHERE LBNUM = 1;
    
--글 수정
UPDATE LEARNME_BOARD SET LBSUBJECT='회원이다', LBCONTENT='이상한 디저트', LBFILENAME01=NULL, LBFILENAME02=NULL, LBFILENAME03=NULL, LBDATE=SYSDATE, LBIP='192.168.10.151' WHERE LBNUM=1; 

--글 삭제
DELETE LEARNME_BOARD WHERE LBNUM=2;

--START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, LB.* FROM (SELECT LB.*, (SELECT CNICK FROM CUSTOMER C WHERE C.CID=LB.CID) CNICK,
    (SELECT ANAME FROM ADMIN_DESSERT A WHERE A.AID=LB.AID) ANAME FROM LEARNME_BOARD LB ORDER BY LBNUM DESC) LB) WHERE RN BETWEEN 1 AND 5;

---------------------    
--글 보기
SELECT * FROM LEARNME_BOARD;






-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
--REPLY TABLE 댓글 삽입

DROP SEQUENCE REPLY_SEQ;
DROP TABLE REPLY;

CREATE SEQUENCE REPLY_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE REPLY(
    RNUM NUMBER(6) PRIMARY KEY,
    LBNUM NUMBER(6) REFERENCES LEARNME_BOARD ON DELETE CASCADE,
    CID VARCHAR2(30) REFERENCES CUSTOMER,
    RMEMO VARCHAR2(1000) NOT NULL,
    RDATE DATE DEFAULT SYSDATE,
    RIP VARCHAR2(20) NOT NULL);

--댓글 보기
SELECT * FROM REPLY;

--댓글 쓰기
INSERT INTO REPLY (RNUM, LBNUM, CID, RMEMO, RIP) VALUES (REPLY_SEQ.NEXTVAL, 1, 'aaa', '댓글댓글', '192.168.10.151');

--댓글 수정
UPDATE REPLY SET RMEMO='수정이닷', RIP='192.168.10.151' WHERE RNUM=1;

--댓글 삭제
DELETE REPLY WHERE RNUM=2;

--start row end row
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT R.*, CNICK FROM REPLY R, CUSTOMER C WHERE R.CID=C.CID AND LBNUM=2 ORDER BY RNUM DESC) A) WHERE RN BETWEEN 1 AND 2;

--댓글뿌리기
SELECT R.*, CNICK FROM REPLY R, CUSTOMER C WHERE R.CID=C.CID AND LBNUM =1 ORDER BY RNUM;

-- 총 글 갯수
SELECT COUNT(*) FROM REPLY;

SELECT * FROM REPLY;
------------------------------------------------------------------------------------------------------------
--EAT ME TABLE
DROP SEQUENCE EATME_SEQ;
DROP TABLE EATME_BOARD;

CREATE SEQUENCE EATME_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE EATME_BOARD(
    EBNUM NUMBER(6) PRIMARY KEY,
    CID VARCHAR(30) REFERENCES CUSTOMER,
    EBSUBJECT VARCHAR(500) NOT NULL,
    EBCONTENT CLOB NOT NULL,
    EBFILENAME01 VARCHAR2(100) NOT NULL,
    EBFILENAME02 VARCHAR2(100),
    EBFILENAME03 VARCHAR2(100),
    EBFILENAME04 VARCHAR2(100),
    EBFILENAME05 VARCHAR2(100),
    EBFILENAME06 VARCHAR2(100),
    EBFILENAME07 VARCHAR2(100),
    EBFILENAME08 VARCHAR2(100),
    EBFILENAME09 VARCHAR2(100),
    EBFILENAME10 VARCHAR2(100),
    EBDATE DATE DEFAULT SYSDATE,
    EBHIT NUMBER(6) DEFAULT 0,
    EBIP VARCHAR2(20) NOT NULL);
    
-- 총 글 갯수
SELECT COUNT(*) FROM EATME_BOARD;

--조회수 올리기
UPDATE EATME_BOARD SET EBHIT = EBHIT + 1 WHERE EBNUM=1;

--상세글 보기
SELECT EB.*, CNICK FROM EATME_BOARD EB, CUSTOMER C WHERE EB.CID=C.CID AND EBNUM=1;
         
--글 작성
INSERT INTO EATME_BOARD(EBNUM, CID, EBSUBJECT, EBCONTENT, EBFILENAME01, EBFILENAME02, EBFILENAME03, EBFILENAME04, EBFILENAME05, EBFILENAME06, EBFILENAME07, EBFILENAME08, EBFILENAME09, EBFILENAME10, EBIP) VALUES 
(EATME_SEQ.NEXTVAL, 'aaa', '제목', '본문', 'LION.PNG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '192.168.10.151');

--수정글 보기
SELECT EB.*, CNICK FROM EATME_BOARD EB, CUSTOMER C WHERE EB.CID = C.CID AND EBNUM = 1;  

--글 수정
UPDATE EATME_BOARD SET EBSUBJECT='TITLE', EBCONTENT='CONTENT', EBFILENAME01='IMADESSERT.PNG', EBFILENAME02='NOIMG.PNG', EBFILENAME03=NULL, EBFILENAME04=NULL, EBFILENAME05=NULL,
EBFILENAME06=NULL, EBFILENAME07=NULL, EBFILENAME08=NULL, EBFILENAME09=NULL, EBFILENAME10=NULL, EBDATE=SYSDATE, EBIP='192.168.0.14' WHERE EBNUM=1;

--글 삭제
DELETE EATME_BOARD WHERE EBNUM=14;

--START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT EB.*, CNICK FROM EATME_BOARD EB, CUSTOMER C WHERE EB.CID=C.CID ORDER BY EBNUM DESC) A) WHERE RN BETWEEN 1 AND 2;    

COMMIT;

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
--COOK ME TABLE
DROP SEQUENCE COOKME_SEQ;
DROP TABLE COOKME_BOARD;

CREATE SEQUENCE COOKME_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE COOKME_BOARD(
    CBNUM NUMBER(6) PRIMARY KEY,
    CID VARCHAR2(30) REFERENCES CUSTOMER,
    CBSUBJECT VARCHAR2(500) NOT NULL,
    CBCONTENT01 CLOB NOT NULL,
    CBCONTENT02 CLOB NOT NULL,
    CBCONTENT03 CLOB NOT NULL,
    CBCONTENT04 CLOB,
    CBCONTENT05 CLOB,
    CBCONTENT06 CLOB,
    CBCONTENT07 CLOB,
    CBCONTENT08 CLOB,
    CBCONTENT09 CLOB,
    CBCONTENT10 CLOB,
    CBFILENAME01 VARCHAR(100) NOT NULL,
    CBFILENAME02 VARCHAR(100) NOT NULL,
    CBFILENAME03 VARCHAR(100) NOT NULL,
    CBFILENAME04 VARCHAR(100),
    CBFILENAME05 VARCHAR(100),
    CBFILENAME06 VARCHAR(100),
    CBFILENAME07 VARCHAR(100),
    CBFILENAME08 VARCHAR(100),
    CBFILENAME09 VARCHAR(100),
    CBFILENAME10 VARCHAR(100),
    CBDATE DATE DEFAULT SYSDATE,
    CBHIT NUMBER(6) DEFAULT 0,
    CBIP VARCHAR2(20) NOT NULL);
    
-- 총 글 갯수
SELECT COUNT(*) FROM COOKME_BOARD;

--조회수 올리기
UPDATE COOKME_BOARD SET CBHIT = CBHIT + 1 WHERE CBNUM=2;

--상세글 보기
SELECT CB.*, CNICK FROM COOKME_BOARD CB, CUSTOMER C WHERE CB.CID=C.CID AND CBNUM=2;
                
--글 작성
INSERT INTO COOKME_BOARD(CBNUM, CID, CBSUBJECT, CBCONTENT01, CBCONTENT02, CBCONTENT03, CBCONTENT04, CBCONTENT05, CBCONTENT06, CBCONTENT07, CBCONTENT08, CBCONTENT09, CBCONTENT10,
 CBFILENAME01, CBFILENAME02, CBFILENAME03, CBFILENAME04, CBFILENAME05, CBFILENAME06, CBFILENAME07, CBFILENAME08, CBFILENAME09, CBFILENAME10, CBIP) VALUES 
(COOKME_SEQ.NEXTVAL, 'aaa', '제목', '본문1', '본문2', '본문3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LION.PNG', 'LION.PNG', 'LION.PNG', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '192.168.10.151');

--수정글 보기
SELECT CB.*, CNICK FROM COOKME_BOARD CB, CUSTOMER C WHERE CB.CID = C.CID AND CBNUM = 1;  

--글 수정
UPDATE COOKME_BOARD SET CBSUBJECT='TITLE', CBCONTENT01='CONTENT01', CBCONTENT02='CONTENT02', CBCONTENT03='CONTENT03', CBCONTENT04='CONTENT04', CBCONTENT05='CONTENT05', CBCONTENT06='CONTENT06', CBCONTENT07='CONTENT07', CBCONTENT08='CONTENT08', CBCONTENT09='CONTENT09', CBCONTENT10='CONTENT10',
CBFILENAME01='IMADESSERT.PNG', CBFILENAME02='NOIMG.PNG', CBFILENAME03='NOIMG.PNG', CBFILENAME04=NULL, CBFILENAME05=NULL,
CBFILENAME06=NULL, CBFILENAME07=NULL, CBFILENAME08=NULL, CBFILENAME09=NULL, CBFILENAME10=NULL, CBDATE=SYSDATE, CBIP='192.168.0.14' WHERE CBNUM=1;

--글 삭제
DELETE COOKME_BOARD WHERE CBNUM=1;

--START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT CB.*, CNICK FROM COOKME_BOARD CB, CUSTOMER C WHERE CB.CID=C.CID ORDER BY CBNUM DESC) A) WHERE RN BETWEEN 1 AND 2;    

-------------------------------------------------------------------------------------------------------------------------------------------
--TALK ME TABLE
DROP SEQUENCE TALKME_SEQ;
DROP TABLE TALKME_BOARD;

CREATE SEQUENCE TALKME_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE TALKME_BOARD(
    TBNUM NUMBER(6) PRIMARY KEY,
    CID VARCHAR(30) REFERENCES CUSTOMER,
    TBSUBJECT VARCHAR(500) NOT NULL,
    TBCONTENT CLOB NOT NULL,
    TBFILENAME01 VARCHAR(100),
    TBFILENAME02 VARCHAR(100),
    TBFILENAME03 VARCHAR(100),
    TBFILENAME04 VARCHAR(100),
    TBFILENAME05 VARCHAR(100),
    TBDATE DATE DEFAULT SYSDATE,
    TBHIT NUMBER(6) DEFAULT 0,
    TBGROUP NUMBER(6) NOT NULL,
    TBSTEP NUMBER(5) NOT NULL,
    TBINDENT NUMBER(5) NOT NULL,
    TBIP VARCHAR2(20) NOT NULL);

-- 총 글 갯수
SELECT COUNT(*) FROM TALKME_BOARD;

--조회수 올리기
UPDATE TALKME_BOARD SET TBHIT = TBHIT + 1 WHERE TBNUM=2;

--상세글 보기
SELECT TB.*, CNICK FROM TALKME_BOARD TB, CUSTOMER C WHERE TB.CID=C.CID AND TBNUM=2;
                
--글 작성
INSERT INTO TALKME_BOARD(TBNUM, CID, TBSUBJECT, TBCONTENT, TBFILENAME01, TBFILENAME02, TBFILENAME03, TBFILENAME04, TBFILENAME05, TBGROUP, TBSTEP, TBINDENT, TBIP) 
VALUES (TALKME_SEQ.NEXTVAL, 'aaa', 'title', 'content', NULL, NULL, NULL, NULL, NULL, TALKME_SEQ.CURRVAL, 0, 0, '192.168.10.151');

--수정글 보기
SELECT TB.*, CNICK FROM TALKME_BOARD TB, CUSTOMER C WHERE TB.CID = C.CID AND TBNUM = 2;  

--글 수정
UPDATE TALKME_BOARD SET TBSUBJECT='TEST TITLE', TBCONTENT='나는 본문이다', TBFILENAME01='NOIMG.PNG', TBFILENAME02='NOIMG.PNG', TBFILENAME03='NOIMG.PNG', TBFILENAME04='NOIMG.PNG', TBFILENAME05='NOIMG.PNG', TBDATE=SYSDATE, TBIP='192.168.10.151' WHERE TBNUM=1;

--글 삭제
DELETE TALKME_BOARD WHERE TBNUM= 1;

--START ROW ~ END ROW 페이지뿌리기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT TB.*, CNICK FROM TALKME_BOARD TB, CUSTOMER C WHERE TB.CID=C.CID ORDER BY TBGROUP DESC, TBSTEP) A) WHERE RN BETWEEN 1 AND 15;    

-- 답변글 추가전 STEP A 수행
UPDATE TALKME_BOARD SET TBSTEP = TBSTEP + 1 WHERE TBGROUP = 1 AND TBSTEP>0;

--답변글 쓰기
INSERT INTO TALKME_BOARD(TBNUM, CID, TBSUBJECT, TBCONTENT, TBFILENAME01, TBFILENAME02, TBFILENAME03, TBGROUP, TBSTEP, TBINDENT, TBIP)
    VALUES (TALKME_SEQ.NEXTVAL, 'aaa', 'TITILE2', 'CONTENT2', NULL, NULL, NULL, 1, 1, 1, '192.168.10.151');

SELECT * FROM TALKME_BOARD;




SELECT * FROM TALKME_BOARD;





COMMIT;